<?php

// $Id$

/**
 * Implementation of hook_menu().
 */
function custom_user_registration_menu() {
  $items = array();

  $items['individual/register/form'] = array(
      'title' => 'Sign Up',
      'page callback' => 'custom_user_registration_for_individual',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );

  return $items;
}

function custom_user_registration_for_individual() {
  $output = '';
  $output.= drupal_get_form('custom_user_registration_form');
  return $output;
}

function custom_user_registration_form() {
  $form['description'] = array(
      '#type' => 'item',
      '#title' => t(''),
  );
  // This is the first form element. It's a textfield with a label, "Name"
  $form['firstname'] = array(
      '#type' => 'textfield',
      '#title' => t('First Name'),
      '#required' => true,
  );

  $form['lastname'] = array(
      '#type' => 'textfield',
      '#title' => t('Last Name'),
      '#required' => true,
  );

  $form['email'] = array(
      '#type' => 'textfield',
      '#title' => t('Email Address'),
      '#required' => true,
  );

  $form['password'] = array(
      '#type' => 'password',
      '#title' => t('Password'),
      '#required' => true,
  );
  $form['cpassword'] = array(
      '#type' => 'password',
      '#title' => t('Confirm Password'),
      '#required' => true,
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Sign Up'),
      '#weight' => '4',
  );

  return $form;
}

function custom_user_registration_form_validate($form, &$form_state) {

//  if( $form_state['values']['firstname'] == ''){
//     $error_msg .= 'First Name field is required.';
//  }
//  if( $form_state['values']['lastname'] == ''){
//    $error_msg .= 'Last Name field is required.';
//  }
//  if( $form_state['values']['email'] == ''){
//    $error_msg .= 'Email Address field is required.';
//  }
  // if( $form_state['values']['password'] == ''){
  //  $error_msg .= 'Password field is required.';
  // }else{
  if (!valid_email_address($form_state['values']['email'])) {
      form_set_error('submitted][email_address', t('The email address appears to be invalid.'));
  }
  
  if(user_validate_mail($form_state['values']['email']))
  {
    //$error_msg .= 'Email Address field is required.';
  }
  
  if ($form_state['values']['cpassword'] == '') {
    //$error_msg .= 'Confirm Password field is required.';
  } else {
    if ($form_state['values']['password'] != $form_state['values']['cpassword']) {
      $error_msg .= 'Password and Confirm Password does not match.';
    }
  }
  // }
//  
 form_error($form, t($error_msg));
}

function custom_user_registration_form_submit($form, &$form_state) {
  $user_name = $form_state['values']['firstname'] . ' ' . $form_state['values']['lastname'];
  $email = $form_state['values']['email'];
  $password = $form_state['values']['password'];
  $fields_arr = array(
      'name' => $user_name,
      'mail' => $email,
      'pass' => $password,
      'status' => 1,
      'roles' => array('authenticated user'),
  );
  user_save(null, $fields_arr);
  drupal_set_message('Your Account Created Successfully.');
}

function custom_user_registration_form_alter(&$form, &$form_state, $form_id) {
  
  if ($form_id == 'user_register') {
    //ms_membership_fieldset
    
    //$form['submit']['#access'] =   false;
    $form['ms_membership']['#weight'] = 50;
    $form['submit']['#weight'] =   -30;
    
    /* Setting Default Plan Code Starts */
    $plantype = $_GET['plantype'];
    $default_plan = 1;
     //dsm($form);
    switch($plantype){
       case 'product':
          $default_plan = 1;
       break;
       case 'restaurant':
          $default_plan = 2;
       break;
       case 'medical':
          $default_plan = 3;
       break;
       case 'business_document':
          $default_plan = 4;
       break;
    }
   
   $form['ms_membership']['mpid']['#default_value'] = $default_plan;
   
   /* Setting Default Plan Code Ends */
   //print_r($form);exit;
  }
}